# Generated by Django 4.1 on 2022-09-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220902_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='excel_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_No', models.CharField(max_length=10, null=True)),
                ('RollNo', models.CharField(max_length=15, null=True)),
                ('Name', models.CharField(max_length=100, null=True)),
                ('GradeR', models.CharField(max_length=100, null=True)),
                ('PointsR', models.CharField(max_length=30, null=True)),
                ('CreditsR', models.CharField(default='', max_length=12, null=True)),
                ('Resc', models.CharField(default='', max_length=500, null=True)),
                ('GradeW', models.CharField(max_length=100, null=True)),
                ('PointsW', models.CharField(max_length=30, null=True)),
                ('CreditsW', models.CharField(default='', max_length=12, null=True)),
                ('web_tech', models.CharField(default='', max_length=500, null=True)),
                ('GradeD', models.CharField(max_length=100, null=True)),
                ('PointsD', models.CharField(max_length=30, null=True)),
                ('CreditsD', models.CharField(default='', max_length=12, null=True)),
                ('Dis_sys', models.CharField(default='', max_length=500, null=True)),
                ('GradeD1', models.CharField(max_length=100, null=True)),
                ('PointsD1', models.CharField(max_length=30, null=True)),
                ('CreditsD1', models.CharField(default='', max_length=12, null=True)),
                ('Design', models.CharField(default='', max_length=500, null=True)),
                ('GradeM', models.CharField(max_length=100, null=True)),
                ('PointsM', models.CharField(max_length=30, null=True)),
                ('CreditsM', models.CharField(default='', max_length=12, null=True)),
                ('Mefa', models.CharField(default='', max_length=500, null=True)),
                ('GradeI', models.CharField(max_length=100, null=True)),
                ('PointsI', models.CharField(max_length=30, null=True)),
                ('CreditsI', models.CharField(default='', max_length=12, null=True)),
                ('Info', models.CharField(default='', max_length=500, null=True)),
                ('Gradew1', models.CharField(max_length=100, null=True)),
                ('Pointsw1', models.CharField(max_length=30, null=True)),
                ('Creditsw1', models.CharField(default='', max_length=12, null=True)),
                ('wlab', models.CharField(default='', max_length=500, null=True)),
                ('sgpa', models.CharField(max_length=5, null=True)),
                ('Tot_cr', models.CharField(max_length=5, null=True)),
                ('pass1', models.CharField(max_length=5, null=True)),
                ('bclg', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
